### ISSUE TITLE
Mux 7-packets alignment

### ISSUE THREAD

**Issue by alexchern** [asticode/go-astits#58]
Hi,

Is it possible to configure a Mux for 7-packets alignment for udp streaming?

Thanks,

Alex

**Comment by asticode** [comment]
Unfortunately the muxer is not configurable to do such a thing

**Comment by impleotv** [comment]
I see... Ok. Will implement it in the StreamWriter (though usually it is a mux config property).
Thanks for your great project!
 Alex

**Comment by alexchern** [comment]
I see... Ok. Will implement it in the StreamWriter (though usually it is a mux config property).
Thanks for your great project!
Alex
