### ISSUE TITLE
[Question]: no PMT in DemuxerData of mpetgs over udp

### ISSUE THREAD

**Issue by Mr3h1v** [asticode/go-astits#59]
When i run `astits-probe packets -d all -i udp://239.0.0.1:10001`, it works ok.

But when i run `astits-probe data -d all -i udp://239.0.0.1:10001`, all of DemuxerData are PAT or SDT 
```
➜  astits-probe git:(master) ✗ ./astits-probe data -d all -i udp://239.0.0.1:10001       
2024/08/31 00:18:57 Fetching data...
2024/08/31 00:19:04 PAT: 0
2024/08/31 00:19:04   Transport Stream ID: 1
2024/08/31 00:19:04   Programs:
2024/08/31 00:19:04     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:04 PAT: 0
2024/08/31 00:19:04   Transport Stream ID: 1
2024/08/31 00:19:04   Programs:
2024/08/31 00:19:04     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:04 PAT: 0
2024/08/31 00:19:04   Transport Stream ID: 1
2024/08/31 00:19:04   Programs:
2024/08/31 00:19:04     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:04 PAT: 0
2024/08/31 00:19:04   Transport Stream ID: 1
2024/08/31 00:19:04   Programs:
2024/08/31 00:19:04     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:05 PAT: 0
2024/08/31 00:19:05   Transport Stream ID: 1
2024/08/31 00:19:05   Programs:
2024/08/31 00:19:05     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:05 PAT: 0
2024/08/31 00:19:05   Transport Stream ID: 1
2024/08/31 00:19:05   Programs:
2024/08/31 00:19:05     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:05 PAT: 0
2024/08/31 00:19:05   Transport Stream ID: 1
2024/08/31 00:19:05   Programs:
2024/08/31 00:19:05     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:05 SDT: 17
2024/08/31 00:19:05 PAT: 0
2024/08/31 00:19:05   Transport Stream ID: 1
2024/08/31 00:19:05   Programs:
2024/08/31 00:19:05     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:05 PAT: 0
2024/08/31 00:19:05   Transport Stream ID: 1
2024/08/31 00:19:05   Programs:
2024/08/31 00:19:05     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:05 PAT: 0
2024/08/31 00:19:05   Transport Stream ID: 1
2024/08/31 00:19:05   Programs:
2024/08/31 00:19:05     &{ProgramMapID:4096 ProgramNumber:1}
2024/08/31 00:19:05 SDT: 17
2024/08/31 00:19:06 PAT: 0
2024/08/31 00:19:06   Transport Stream ID: 1
2024/08/31 00:19:06   Programs:
2024/08/31 00:19:06     &{ProgramMapID:4096 ProgramNumber:1}
```

The udp stream is generated by this command
```
ffmpeg -re -stream_loop -1 -i .\h264.mp4 -c copy -f mpegts -mpegts_flags pat_pmt_at_frames "udp://239.0.0.1:10001?pkt_size=1316"
```

[h265.mp4](https://github.com/user-attachments/assets/ad7e893d-93b7-477c-bac5-bf66b5d8d03d)

**Comment by asticode** [comment]
`astits`'s demuxer doesn't handle discontinuities between packets which means your example will work fine if you transmux your file to a `.ts` file but won't work if you read from UDP as PES packets arrive out of order. [This part](https://github.com/asticode/go-astits/blob/master/packet_pool.go#L23) would need to be reworked to handle discontinuities better.

Also what I find weird is that I see no PMT packets in the UDP stream whereas I can see some in the transmuxed file but I don't know whether this is due to the ffmpeg command 🤔

**Comment by Mr3h1v** [comment]
Thanks for your explanation.

And another question that I'am wondering is, how can i mux video frames data  into a TS over udp stream that complies with the DVB standard (PCR interval less than 40ms).

**Comment by asticode** [comment]
If your PMT's PCR PID is properly [set](https://github.com/asticode/go-astits/blob/master/muxer.go#L157) and you actually provide a PCR value in the packets with that PID, you can [change the tables retransmit interval](https://github.com/asticode/go-astits/blob/master/muxer.go#L65) to whatever value you see fit. Unless I've missed something, that should do the trick.

**Comment by Mr3h1v** [comment]
Thanks.
