### ISSUE TITLE
PES parsing fails with out of range index

### ISSUE THREAD

**Issue by Hakkin** [asticode/go-astits#7]
Using the provided example program in master, I get an error trying to dump PES info.
```
ERRO[0000] astits: fetching data failed: astits: getting next data failed: astits: building new data failed: astits: parsing PES data failed: astits: getting next bytes failed: astits: slice length is 15922, offset 15935 is invalid
```

This seems to have broke @https://github.com/asticode/go-astits/commit/8d58895ff21f7636d41169fad8e71d93de72fff7.

[Here's an example ts that triggers this if you need it.](https://github.com/asticode/go-astits/files/3616845/test.zip)

The command I'm running is `astits data -d all -i test.ts`

**Comment by asticode** [comment]
First off, thanks for providing an example file 👍 

Second, was everything working before https://github.com/asticode/go-astits/commit/8d58895ff21f7636d41169fad8e71d93de72fff7?

**Comment by Hakkin** [comment]
Yes, I checked out @https://github.com/asticode/go-astits/commit/f5a59e81bd788a89eeb071500063292220219864 and the same command works fine.

**Comment by asticode** [comment]
Never mind, there was indeed a problem. Should be all good now!

Can you confirm?

**Comment by Hakkin** [comment]
Yes, that seems to have fixed it. Thanks for the quick patch!

**Comment by asticode** [comment]
Cheers
