### ISSUE TITLE
End of PES payload is truncated for certain streams

### ISSUE THREAD

**Issue by Hakkin** [asticode/go-astits#8]
I'm trying to extract timed ID3 data, which contains a JSON payload, but the end of every PES payload seems to be truncated by a few bytes. This also happens when attempting to extract the AAC audio (results in a corrupted file), the H264 stream seems to extract fine though.

I've compared this to extracting the data using ffmpeg (`ffmpeg -i test.ts -map 0:2 -c copy -f data ID3.bin`), ffmpeg actually has it's own issues in that it doesn't output the magic number at the start of the stream for whatever reason, but it seems to correctly extract the payload otherwise.

[Here is an example ts file to use,](https://github.com/asticode/go-astits/files/3655188/test.zip)
[and here is the extracted ID3 stream using astits vs ffmpeg](https://github.com/asticode/go-astits/files/3655194/extracted.zip). You can see the first payload astits extracted ends in `"transc_s":15694516`, while ffmpeg is `"transc_s":1569451686155}`

You can see the code I'm using to extract the PES payload here: https://gist.github.com/Hakkin/6cab34dcf004494d436025a1846633c0
It's possible I'm doing something wrong in my code, but it seems fairly straightforward, so I'm not sure.

**Comment by asticode** [comment]
Thanks for providing the data to reproduce the problem, I'll check it out!

**Comment by asticode** [comment]
@Hakkin I've pushed a fix, it should be all good now (even for AAC). Can you confirm?

**Comment by Hakkin** [comment]
That seems to have fixed the payloads being truncated, but now I've noticed that astits isn't outputting as much stream data as ffmpeg does. In the example file above, astits outputs 4096 bytes, ffmpeg outputs 5005 bytes. Inspecting the data, I can see astits seems to be skipping some packets at the end of the stream.

**Comment by Hakkin** [comment]
Oops, sorry! That was an issue with my code, not yours. I wasn't flushing my buffer properly. This seems to be fixed. Thank you!

**Comment by asticode** [comment]
Cheers
